#!/bin/sh

# check if not an amend
if [[ $(cat $1) =~ ^\[[a-zA-Z]+-[0-9]+\] ]];
then
	exit 0
fi

# get current branch
branchName=`git rev-parse --abbrev-ref HEAD`

# search jira issue id in a pattern such a "feature/ABC-123-description"
jiraId=$(echo $branchName | perl -C -n -e '/[a-z]+\/([A-Z0-9]+-[0-9]+)[-_[:alnum:]_[:space:]\.\(\)-[:punct:]\p{So}]+/ && print $1')

# only prepare commit message if pattern matched and jiraId was found
if [[ ! -z $jiraId ]]; then
	bak=$(cat $1)
	joined="[$jiraId] $bak"
	# $1 is the name of the file containing the commit message
	echo $joined > $1
fi
